// Sample data for the seating arrangement
const internatData = [
    { nom: "Ambou", prenom: "Thomas Thierry Fils", seat: "A1" },
    { nom: "Bakayoko Tênêna", prenom: "Mamadou", seat: "A2" },
    { nom: "Buduk B. Joof", prenom: "Awa", seat: "A3" },
    { nom: "Conde", prenom: "Alpha", seat: "A4" },
    { nom: "Daffe", prenom: "Sekou", seat: "A5" },
    { nom: "Diallo", prenom: "Aiba", seat: "A6" },
    { nom: "Djiddo Guildja", prenom: "Tchari", seat: "A7" },
    { nom: "Indeque Malaca", prenom: "Carlos", seat: "A8" },
    { nom: "Mamadou", prenom: "Oumar Gueye", seat: "A9" },
    { nom: "Misengui", prenom: "Paul Bruno", seat: "A10" },
    { nom: "Mugemana", prenom: "Hugues", seat: "B1" },
    { nom: "Ndongala", prenom: "Niclette", seat: "B2" },
    { nom: "Nguema Nsue Mbang", prenom: "Alberto", seat: "B3" },
    { nom: "Nzambimana", prenom: "Eric", seat: "B4" },
    { nom: "RANDRIAMAMPIANINA", prenom: "Nandrianina Fankasitrahana", seat: "B5" },
    { nom: "Santana Tavares", prenom: "Marilene", seat: "B6" },
    { nom: "Toihir", prenom: "Nasfat", seat: "B7" },
    { nom: "Zeon", prenom: "Yongbladeh Praise", seat: "B8" }
];

const promoData = [
    { nom: "ABARKI", prenom: "AMINE", seat: "A1" },
    { nom: "ABCHIR", prenom: "Zineb", seat: "A2" },
    { nom: "ABDEDAIM", prenom: "AYA", seat: "A3" },
    { nom: "Abidi", prenom: "Siham", seat: "A4" },
    { nom: "AKHSAS", prenom: "HAJAR", seat: "A5" },
    { nom: "Alsafi", prenom: "Salma", seat: "A6" },
    { nom: "Asatach", prenom: "Hafssa", seat: "A7" },
    { nom: "BEN AHMIDA", prenom: "Achraf", seat: "A8" },
    { nom: "Ben Laarbi", prenom: "Hanan", seat: "A9" },
    { nom: "BENALI", prenom: "Zouhair", seat: "A10" },
    { nom: "Benbrahim", prenom: "Ilyas", seat: "B1" },
    { nom: "BENHAMOU", prenom: "Selma", seat: "B2" },
    { nom: "Benkhadra", prenom: "Mohamed Reda", seat: "B3" },
    { nom: "Benkirane", prenom: "Zineb", seat: "B4" },
    { nom: "Berrada", prenom: "Chadi", seat: "B5" },
    { nom: "Bettach", prenom: "Ibtissam", seat: "B6" },
    { nom: "BIRAT", prenom: "Salma", seat: "B7" },
    { nom: "Bouchenafa", prenom: "Oussama", seat: "B8" },
    { nom: "BOUDERK", prenom: "BOUBKER", seat: "B9" },
    { nom: "Bouleknadel", prenom: "Abdeladim", seat: "B10" },
    { nom: "CHIRAJE", prenom: "Hiba", seat: "C1" },
    { nom: "CHOUARI", prenom: "WALID", seat: "C2" },
    { nom: "El aagouby", prenom: "Soufiane", seat: "C3" },
    { nom: "El Abbassi", prenom: "Mohamed Amine", seat: "C4" },
    { nom: "EL AISSAOUI", prenom: "Chaima", seat: "C5" },
    { nom: "El Aouni", prenom: "Soufia", seat: "C6" },
    { nom: "El asraoui", prenom: "Oumaima", seat: "C7" },
    { nom: "EL BAGHDADI", prenom: "REDA", seat: "C8" },
    { nom: "El Ghazy", prenom: "Mohamed", seat: "C9" },
    { nom: "EL KOHLI", prenom: "Othmane", seat: "C10" },
    { nom: "El kouraichi", prenom: "Abdellah", seat: "D1" },
    { nom: "EL MEZZI", prenom: "Youness", seat: "D2" },
    { nom: "EL MOSSAOUI", prenom: "Salssabil", seat: "D3" },
    { nom: "ELKHILI", prenom: "Mokhtar", seat: "D4" },
    { nom: "ENNACIRI", prenom: "Oumayma", seat: "D5" },
    { nom: "Errbiza", prenom: "Isslame", seat: "D6" },
    { nom: "ES-SIFER", prenom: "Alae-eddine", seat: "D7" },
    { nom: "FAHIL", prenom: "Chaimae", seat: "D8" },
    { nom: "FAHRAOUI", prenom: "JIHANE", seat: "D9" },
    { nom: "Firdaoussi", prenom: "Khadija", seat: "D10" },
    { nom: "GOUDDAR", prenom: "YOUSSRA", seat: "E1" },
    { nom: "Gourja", prenom: "Khaoula", seat: "E2" },
    { nom: "Hamri", prenom: "Zineb", seat: "E3" },
    { nom: "Inirfed", prenom: "Meriem", seat: "E4" },
    { nom: "Iraqui", prenom: "Abla", seat: "E5" },
    { nom: "Kabbar", prenom: "Khalid", seat: "E6" },
    { nom: "Kalam Idrissi", prenom: "Mohammed", seat: "E7" },
    { nom: "Kerdad", prenom: "Soukaina", seat: "E8" },
    { nom: "Khail", prenom: "Hajar", seat: "E9" },
    { nom: "Lachhab", prenom: "Imane", seat: "E10" },
    { nom: "LACHQER", prenom: "Farah", seat: "F1" },
    { nom: "Lafnich", prenom: "Rachid", seat: "F2" },
    { nom: "Lahmoum", prenom: "Imane", seat: "F3" },
    { nom: "Lemghari", prenom: "Zineb", seat: "F4" },
    { nom: "MAATOUF", prenom: "Noufel", seat: "F5" },
    { nom: "Macbahi", prenom: "Badr", seat: "F6" },
    { nom: "Machhour", prenom: "Houssam", seat: "F7" },
    { nom: "MAKHLOUF", prenom: "Khalid", seat: "F8" },
    { nom: "Marhfour", prenom: "Sara", seat: "F9" },
    { nom: "MASHI", prenom: "Chaimaa", seat: "F10" },
    { nom: "MICHA", prenom: "Loubna", seat: "G1" },
    { nom: "Mirouad", prenom: "Hamza", seat: "G2" },
    { nom: "Naciri", prenom: "Ilyas", seat: "G3" },
    { nom: "Oudouni", prenom: "Yousra", seat: "G4" },
    { nom: "RABHI", prenom: "MOHAMMED", seat: "G5" },
    { nom: "ZAHID", prenom: "Amine", seat: "G6" },
    { nom: "ZAKRARI", prenom: "Ali", seat: "G7" },
    { nom: "ZBADI", prenom: "Mohamed", seat: "G8" },
    { nom: "ZENBOURI", prenom: "Oussama", seat: "G9" }
];